### ISSUE TITLE
Публикуем версию сайта v. 0.1

### ISSUE THREAD

**Issue by m0lchanoff** [veck-messel/veck-messel.github.io#2]

**Comment by m0lchanoff** [comment]
Попробуйте пул реквест залинковать с этой задачей.

**Comment by m0lchanoff** [comment]
![Image](https://user-images.githubusercontent.com/50970383/230594729-0d350b90-be72-4ab1-8018-0fd8a6b99fe1.png)

**Comment by ArturPimenov** [comment]
Поправлю сейчас, не заметил

**Comment by ArturPimenov** [comment]
Там всё плохо с ссылками было, мэйн поправил, щас залью

**Comment by ArturPimenov** [comment]
Все пути поправил, это был кринж, но я справился 😵‍💫

**Comment by m0lchanoff** [comment]
![image](https://user-images.githubusercontent.com/50970383/230630767-2f51a1c1-fccb-4c64-9ba3-e62a1ab8ac43.png)

а когда выкатим след версию?

**Comment by ArturPimenov** [comment]
Всё вижу) я с ссылками долго возился и картинки генерил (с картинками всё плохо). Отошёл ненадолго, а то чет устал возится с этой пупой

**Comment by m0lchanoff** [comment]
Попробуем проскочить с ней. Вроде, решение должно быть до 20ого апреля.
